//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadWiki.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnergiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnergiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PadWiki.WebApp.Resources.EnergiesResources", typeof(EnergiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        internal static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        internal static string Dragon {
            get {
                return ResourceManager.GetString("Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        internal static string Electric {
            get {
                return ResourceManager.GetString("Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy.
        /// </summary>
        internal static string Fairy {
            get {
                return ResourceManager.GetString("Fairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        internal static string Fighting {
            get {
                return ResourceManager.GetString("Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying.
        /// </summary>
        internal static string Flying {
            get {
                return ResourceManager.GetString("Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost.
        /// </summary>
        internal static string Ghost {
            get {
                return ResourceManager.GetString("Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        internal static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        internal static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychic.
        /// </summary>
        internal static string Psychic {
            get {
                return ResourceManager.GetString("Psychic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        internal static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
