//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadWiki.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PadWiki.WebApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        internal static string BoostStages {
            get {
                return ResourceManager.GetString("BoostStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordered.
        /// </summary>
        internal static string Bordered {
            get {
                return ResourceManager.GetString("Bordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown.
        /// </summary>
        internal static string Cooldown {
            get {
                return ResourceManager.GetString("Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dense.
        /// </summary>
        internal static string Dense {
            get {
                return ResourceManager.GetString("Dense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Rate.
        /// </summary>
        internal static string ExperienceRate {
            get {
                return ResourceManager.GetString("ExperienceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover.
        /// </summary>
        internal static string Hover {
            get {
                return ResourceManager.GetString("Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting grounds.
        /// </summary>
        internal static string HuntingGrounds {
            get {
                return ResourceManager.GetString("HuntingGrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be working on updating and enhancing the page you are currently visiting, providing soon detailed and accurate information on the subject..
        /// </summary>
        internal static string IncommingImprovement {
            get {
                return ResourceManager.GetString("IncommingImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingProcess {
            get {
                return ResourceManager.GetString("LoadingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string NoMatchingRecordsFound {
            get {
                return ResourceManager.GetString("NoMatchingRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only players with VIP account (DACC).
        /// </summary>
        internal static string OnlyPlayersWithVIPAccount {
            get {
                return ResourceManager.GetString("OnlyPlayersWithVIPAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other requirements.
        /// </summary>
        internal static string OtherRequirements {
            get {
                return ResourceManager.GetString("OtherRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Rate.
        /// </summary>
        internal static string ProfitRate {
            get {
                return ResourceManager.GetString("ProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required level.
        /// </summary>
        internal static string RequiredLevel {
            get {
                return ResourceManager.GetString("RequiredLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Per Page.
        /// </summary>
        internal static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Striped.
        /// </summary>
        internal static string Striped {
            get {
                return ResourceManager.GetString("Striped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Types Here.
        /// </summary>
        internal static string SuggestedTypesHere {
            get {
                return ResourceManager.GetString("SuggestedTypesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topography.
        /// </summary>
        internal static string Topography {
            get {
                return ResourceManager.GetString("Topography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage info.
        /// </summary>
        internal static string UsageInfo {
            get {
                return ResourceManager.GetString("UsageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works on.
        /// </summary>
        internal static string WorksOn {
            get {
                return ResourceManager.GetString("WorksOn", resourceCulture);
            }
        }
    }
}
